### ISSUE TITLE
Q_KEY nil value error

### ISSUE THREAD

**Issue by JiriAtanasovsky** [Zetosoft/dynacam#1]
When run in Solar2D simulator, writes error:

quantum.lua:70: attempt to perform arithmetic on a nil value

It seems to be caused by this line:
local Q_KEY = string.format("%x", tonumber(string.match(tostring(quantum), "(0x.*)")) + 16)

It seems to "work" when commenting the line out. I would like to fix this but I dont know purpuse of this variable... It seems I can use any string there?

Same goes for dynacam.lua on line 36.

Thanks

**Comment by CetoBasilius** [comment]
The Q_KEY variable is meant to prevent developers from calling `quantum.newLight()` instead of `dynacam.newLight()` You can temporarily change the string to anything in both files as long as it is the same string. Dynacam has not been tested extensively with Solar2D yet, but will be soon! Will leave this open and have an appropriate fix soon.

**Comment by CetoBasilius** [comment]
@JiriAtanasovsky Could you change the line to

```lua
local qString = tostring(quantum)
local qStringMatch = string.match(qString, "(0x.*)")
local qNumber = tonumber(qString)
local Q_KEY = string.format("%x", qNumber + 16)
```

And see on what line of these it crashes? I can't seem to reproduce your results using Solar2D build 2021.3637 (2021.2.3) on MacOS. More information on your version and operating system will help!
